disabled_rules:
  - todo
  - multiple_closures_with_trailing_closure
  - nesting
  - identifier_name
  - type_name
  - operator_usage_whitespace # This has a few bugs that are annoying
  - function_parameter_count # We are too far gone... revisit again in near future
  - line_length
  - vertical_parameter_alignment
  - unused_optional_binding
  - shorthand_operator
opt_in_rules:
  - opening_brace
  - vertical_whitespace
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

